<?php

namespace AppBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    public function getInfos($id){
        $em = $this->getEntityManager();
        $repository = $em->getRepository('AppBundle:Game');
        $query = $repository->createQueryBuilder('i')
            ->select('i.homeTeam')
            ->addSelect('i.awayTeam')
            ->where("i.apiId = :id")
            ->setParameter('id',$id)
            ->getQuery();
        $result = $query->getResult();

        return $result;
    }
    
}
