<?php

namespace AppBundle\Repository;

/**
 * LastUpdatedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LastUpdatedRepository extends \Doctrine\ORM\EntityRepository
{
}
